# How GitHub groups merged pull requests in the notes of a release
changelog:
  exclude:
    labels: [skip-release-notes]
  categories:
    - title: New
      labels: [enhancement]
    - title: Fixed
      labels: [bug]
    - title: Guides and website
      labels: [documentation]
    - title: Updated dependencies
      labels: [dependencies]
    - title: Other changes
      labels: ["*"]
