//! Localization (English, Traditional Chinese).
//!
//! Source text is English: `t("{n} item selected|{n} items selected", { n })`. English uses the source text as is;
//! Traditional Chinese looks it up in the zh-TW dictionary and falls back to the English source when missing.
//! - Parameters are written as `{name}`; English plurals are `single|plural`, picked by `n` (or `count`)
//! - Number parameters are formatted for the locale (1,234); write whole sentences, not pieces joined in code
//! - `tc(context, "English")` is for English text that needs different Chinese in different places (key `context::English`)
//! - Messages returned by the server (errors, activity log details…) are English; `tServer()` translates them:
//!   exact match first, then templates with parameters
//! - The language is decided at load time (so module-level constants can call t); switching reloads the page

export type Lang = "zh-TW" | "en";

export const LANGS: { id: Lang; label: string }[] = [
  { id: "zh-TW", label: "繁體中文" }, // i18n-ignore: language name shown in its own language
  { id: "en", label: "English" },
];

const KEY = "tf-lang";

declare global {
  interface Window {
    /** System default language set by an administrator, injected by the server into the home page HTML (absent = follow the browser) */
    __TF_DEFAULT_LANG__?: string;
  }
}

/** Order: the user's own choice, then the system default, then the browser language */
function detect(): Lang {
  try {
    const saved = localStorage.getItem(KEY);
    if (saved === "zh-TW" || saved === "en") return saved;
  } catch {
    // storage unavailable: fall back to the system default / browser language
  }
  const preset = typeof window !== "undefined" ? window.__TF_DEFAULT_LANG__ : undefined;
  if (preset === "zh-TW" || preset === "en") return preset;
  const nav = typeof navigator !== "undefined" ? (navigator.languages?.[0] ?? navigator.language ?? "") : "";
  return nav.toLowerCase().startsWith("zh") ? "zh-TW" : "en";
}

declare global {
  interface Window {
    /** Dictionary script the server adds to the page for Chinese visitors (dist/zh-TW.js) */
    __TF_ZH__?: { ZH: Record<string, string> };
  }
}

export const lang: Lang = detect();

/**
 * Traditional Chinese dictionary: the script the server put on the page, if any, else empty until `loadDictionary()`
 * fetched it (English users never download it)
 */
let ZH: Record<string, string> = (typeof window !== "undefined" && window.__TF_ZH__?.ZH) || {};

/**
 * Load the dictionary for the active language. Called by main.tsx before the app's modules are evaluated.
 * Usually the server already put the dictionary on the page (no extra round trip); otherwise it's fetched now.
 */
export async function loadDictionary() {
  if (lang !== "zh-TW") return;
  const preloaded = typeof window !== "undefined" ? window.__TF_ZH__?.ZH : undefined;
  ZH = preloaded ?? (await import("@/lib/i18n/zh-TW")).ZH;
}
/**
 * Locale used by Intl. English follows the browser's region when it is an English one (en-GB: day/month/year and
 * 24-hour times), else en-US
 */
function englishLocale() {
  const nav = typeof navigator !== "undefined" ? (navigator.languages?.[0] ?? navigator.language ?? "") : "";
  if (!nav.toLowerCase().startsWith("en")) return "en-US";
  try {
    return Intl.DateTimeFormat.supportedLocalesOf([nav])[0] ?? "en-US";
  } catch {
    return "en-US"; // malformed language tag
  }
}

export const locale = lang === "en" ? englishLocale() : "zh-TW";

if (typeof document !== "undefined") {
  document.documentElement.lang = lang === "en" ? "en" : "zh-Hant";
  // Files generated by the server (CSV exports etc.) use this cookie to pick the language. Only an explicit choice
  // (setLang) also sets tf_lang_chosen: without it the server keeps following the system default language
  document.cookie = `tf_lang=${lang}; path=/; max-age=31536000; SameSite=Lax`;
}

export function setLang(next: Lang) {
  if (next === lang) return;
  try {
    localStorage.setItem(KEY, next);
  } catch {
    // storage unavailable: only affects this page load
  }
  document.cookie = `tf_lang=${next}; path=/; max-age=31536000; SameSite=Lax`;
  document.cookie = "tf_lang_chosen=1; path=/; max-age=31536000; SameSite=Lax";
  window.location.reload();
}

type Vars = Record<string, string | number | null | undefined>;

/** Insert parameters; numbers get the locale's digit grouping (1,234 items) */
function fill(text: string, vars?: Vars) {
  if (!vars) return text;
  return text.replace(/\{(\w+)\}/g, (m, k: string) => {
    const v = vars[k];
    if (v === undefined || v === null) return m;
    return typeof v === "number" ? v.toLocaleString(locale) : v;
  });
}

/** English plurals: `single|plural`, picked by n (plural when there is no n) */
function plural(text: string, vars?: Vars) {
  const bar = text.indexOf("|");
  if (bar < 0) return text;
  const n = vars?.n ?? vars?.count;
  return Number(n) === 1 ? text.slice(0, bar) : text.slice(bar + 1);
}

const missing = new Set<string>();

function lookup(key: string, fallback: string, vars?: Vars) {
  const zh = ZH[key];
  if (zh === undefined) {
    if (import.meta.env.DEV && !missing.has(fallback)) {
      missing.add(fallback);
      console.warn("[i18n] Missing Traditional Chinese translation:", fallback);
    }
    return fill(plural(fallback, vars), vars);
  }
  return fill(zh, vars);
}

/** Translate UI text (the key is the English source text) */
export function t(en: string, vars?: Vars): string {
  if (lang === "en") return fill(plural(en, vars), vars);
  return lookup(en, en, vars);
}

/**
 * For English text that needs different Chinese in different places
 * (e.g. "Unlimited" takes a longer Chinese wording in forms but a shorter one in tables).
 * The dictionary key is `context::English`; falls back to the plain key.
 */
export function tc(context: string, en: string, vars?: Vars): string {
  if (lang === "en") return fill(plural(en, vars), vars);
  const key = `${context}::${en}`;
  return lookup(ZH[key] !== undefined ? key : en, en, vars);
}

// ───────────── Server messages ─────────────

interface Template {
  re: RegExp;
  names: string[];
  zh: string;
  /** Length of the fixed text (parameters excluded) */
  fixed: number;
}

let exact: Map<string, string> | null = null;
let templates: Template[] | null = null;

/** Every English form of a dictionary key: `single|plural` keys give both forms */
const forms = (key: string) => (key.includes("|") ? key.split("|") : [key]);

/** Build the lookup tables once: exact messages and templates from keys with parameters */
function build() {
  exact = new Map();
  const list: Template[] = [];
  for (const [key, zh] of Object.entries(ZH)) {
    if (key.includes("::")) continue;
    for (const en of forms(key)) {
      if (!/\{\w+\}/.test(en)) {
        exact.set(en, zh);
        continue;
      }
      const names: string[] = [];
      const pattern = en
        .split(/(\{\w+\})/)
        .map((part) => {
          const m = /^\{(\w+)\}$/.exec(part);
          if (m) {
            names.push(m[1]);
            // counts only match numbers, so "{n} files" can't swallow arbitrary text
            return m[1] === "n" || m[1] === "count" ? "(\\d[\\d,.]*)" : "([\\s\\S]+?)";
          }
          return part.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
        })
        .join("");
      list.push({ re: new RegExp(`^${pattern}$`), names, zh, fixed: en.replace(/\{\w+\}/g, "").length });
    }
  }
  // Templates with more fixed text are tried first, so loose ones like "{a}: {b}" don't win
  templates = list.sort((a, b) => b.fixed - a.fixed);
}

/** Parameters that carry a whole nested message (e.g. "Connection test failed: {error}") */
const NESTED = new Set(["error", "detail", "reason", "message"]);
/** Parameters that carry a list of fragments joined with ", " (e.g. "{username}: {changes}") */
const LISTS = new Set(["changes", "providers"]);

/** Translate a parameter value: known terms, lists of known terms (joined with the Chinese enumeration comma U+3001), and nested messages */
function fragment(name: string, v: string, depth: number): string {
  const hit = exact!.get(v);
  if (hit !== undefined) return hit;
  if (v.includes(", ")) {
    const parts = v.split(", ");
    const zh = parts.map((p) => exact!.get(p));
    if (LISTS.has(name) || zh.every((z) => z !== undefined)) return parts.map((p, i) => zh[i] ?? p).join("、"); // i18n-ignore: Chinese list separator
  }
  if (NESTED.has(name) && depth < 2) return translate(v, depth + 1);
  return v;
}

function translate(msg: string, depth: number): string {
  const hit = exact!.get(msg);
  if (hit !== undefined) return hit;
  for (const tpl of templates!) {
    const m = tpl.re.exec(msg);
    if (!m) continue;
    const vars: Vars = {};
    tpl.names.forEach((name, i) => {
      vars[name] = fragment(name, m[i + 1], depth);
    });
    return fill(tpl.zh, vars);
  }
  return msg;
}

/**
 * Translate an English message returned by the server (errors, activity log details, connection failure reasons…).
 * Parameter values that are themselves known terms (e.g. "My files"), lists of such terms, and nested error
 * messages are translated too.
 */
export function tServer(msg: string | null | undefined): string {
  if (!msg) return msg ?? "";
  if (lang === "en") return msg;
  if (!exact) build();
  // A message without an exact match is tried against every pattern: remember the result (log pages repeat the
  // same details on every render)
  let out = serverCache.get(msg);
  if (out === undefined) {
    if (serverCache.size >= 2000) serverCache.clear();
    out = translate(msg, 0);
    serverCache.set(msg, out);
  }
  return out;
}

const serverCache = new Map<string, string>();
