/**
 * Shared rendering state: the whole document (DocCtx) and the content area currently being laid out (Flow: body, header/footer, table cell, text box, footnote).
 */

import type { OoxmlPackage, Rel } from "../core/package";
import type { Theme } from "../core/theme";
import type { Numbering } from "./numbering";
import type { Section } from "./section";
import type { Styles, TabStop } from "./styles";

export interface Settings {
  /** Default tab stop interval (twips) */
  defaultTab: number;
  evenAndOdd: boolean;
  /** Script used for the theme's East Asian font (Hant, Hans, Jpan, Hang) */
  script: string;
  lang: string;
  /** Compatibility mode (15 = Word 2013 and later) */
  compat: number;
  footnoteFmt: string | null;
  endnoteFmt: string | null;
}

/** A tab whose width can only be computed after layout */
export interface TabRef {
  el: HTMLElement;
  p: HTMLElement;
  /** Paragraph margin-left (px), used to recover the start of the text column */
  pLeft: number;
  /** Paragraph left indent (px): implicit tab stop on the first line of a hanging-indent paragraph */
  indent: number;
  stops: { pos: number; val: string; leader?: string }[];
  defaultTab: number;
  /** Absolute position tab (w:ptab): alignment and reference width */
  ptab?: { align: string; width: number };
}

/** Extra info about a body block (used for pagination) */
export interface BlockMeta {
  keepNext?: boolean;
  /** Paragraph space before (px): the part kept at the top of a page */
  before?: number;
  /** Referenced footnote ids */
  notes?: string[];
  /** Table: number of header rows */
  headerRows?: number;
  /** Keep paragraph lines together */
  keepLines?: boolean;
  /** Widow/orphan control */
  widow?: boolean;
}

/** A floating object positioned relative to the page (its page is known only after layout) */
export interface PageFloat {
  el: HTMLElement;
  /** Anchor paragraph */
  anchor: HTMLElement;
}

export interface NoteRef {
  kind: "foot" | "end";
  id: string;
  mark: string;
}

export class DocCtx {
  readonly pending: Promise<unknown>[] = [];
  readonly tabs: TabRef[][] = [];
  readonly scaled: HTMLElement[] = [];
  readonly blockMeta = new WeakMap<Element, BlockMeta>();
  readonly noteRefs: NoteRef[] = [];
  /** Pre-rendered SmartArt drawings (part|dm relationship id → drawing XML) */
  readonly diagrams = new Map<string, Document | null>();
  numberingPart: string | null = null;
  footCount = 0;
  endCount = 0;
  constructor(
    readonly pkg: OoxmlPackage,
    readonly theme: Theme | null,
    readonly styles: Styles,
    readonly numbering: Numbering,
    readonly settings: Settings,
    readonly rels: Map<string, Rel[]>,
    readonly footnotes: Map<string, Element>,
    readonly endnotes: Map<string, Element>,
  ) {}

  meta(el: Element): BlockMeta {
    let m = this.blockMeta.get(el);
    if (!m) {
      m = {};
      this.blockMeta.set(el, m);
    }
    return m;
  }
}

/** State of a complex field (fldChar begin/separate/end); may span paragraphs */
export interface FieldState {
  instr: string;
  phase: "code" | "result";
  type: string;
  /** Hide the field result (PAGE etc. are generated by us) */
  suppress: boolean;
  emitted: boolean;
  ffData: Element | null;
  /** Hyperlink field: create a link element in each paragraph */
  link?: () => HTMLElement;
}

export interface TableStyleRef {
  id: string;
  conds: string[];
}

export interface Flow {
  doc: DocCtx;
  /** Current part (relationships are resolved against it) */
  part: string;
  rels: Rel[];
  section: Section;
  /** Available width (px) */
  width: number;
  story: "body" | "header" | "footer" | "note" | "textbox" | "comment";
  depth: number;
  tableStyle?: TableStyleRef;
  inCell?: boolean;
  fields: FieldState[];
  comments: Set<string>;
  /** Floating objects positioned relative to the page */
  floats: PageFloat[];
  /** Footnotes referenced by the current block (collected by the block renderer) */
  notes?: string[];
  /** Default text color inside a text box (the shape style's fontRef) */
  color?: string;
  /** Number to show for footnoteRef inside footnote content */
  noteMark?: string;
  /**
   * Editing (editor.ts): the id of a run whose text can be edited. Its text is marked with the id (`data-r`), never
   * joined with another run's, and its tabs are tab characters rather than laid-out gaps
   */
  edit?: { runId(r: Element): number | undefined };
}

export function childFlow(f: Flow, patch: Partial<Flow>): Flow {
  return { ...f, fields: [], comments: new Set(f.comments), tableStyle: undefined, inCell: false, ...patch };
}

export type { TabStop };
