import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { GlobeIcon, Loader2Icon, UserIcon, UsersIcon, XIcon } from "lucide-react";
import { toast } from "sonner";
import { api, type Grant, type Principal, type PrincipalType, type Role } from "@/api";
import { keys } from "@/api/queryKeys";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { ErrorText } from "@/components/dialogs";
import { Pending } from "@/components/ErrorState";
import { useConfirm } from "@/components/confirm";
import { ROLE_HINT, ROLE_LABEL, atLeast } from "@/lib/drives";
import { refreshFiles } from "@/lib/queries";
import { useMe } from "@/lib/session";
import { cn, formatDate } from "@/lib/utils";
import { t, tServer, tc } from "@/lib/i18n";
import { NativeSelect } from "@/components/ui/native-select";

const PRINCIPAL_ICON = { user: UserIcon, group: UsersIcon, everyone: GlobeIcon } as const;

const EXPIRY = [
  { label: t("No expiration"), days: 0 },
  { label: t("{n} day|{n} days", { n: 7 }), days: 7 },
  { label: t("{n} day|{n} days", { n: 30 }), days: 30 },
  { label: t("{n} day|{n} days", { n: 90 }), days: 90 },
];

/** Names of "Everyone" and deleted principals are generated by the server and need translating; account and group names stay as-is */
/** Role shown next to a user in search results (the server sends "Administrator" or "User"; the list uses the short "Admin") */
const roleDetail = (detail: string) => (detail === "Administrator" ? t("Admin") : tServer(detail));
const principalName = (g: Grant) => (g.principal_type === "everyone" || g.principal_name === "(deleted)" ? tServer(g.principal_name) : g.principal_name);

function PrincipalPicker(props: { value: Principal | null; onChange(p: Principal | null): void; allowEveryone: boolean }) {
  const [q, setQ] = useState("");
  const [debounced, setDebounced] = useState("");
  const [open, setOpen] = useState(false);
  useEffect(() => {
    const timer = setTimeout(() => setDebounced(q), 200);
    return () => clearTimeout(timer);
  }, [q]);
  const results = useQuery({ queryKey: keys.directory(debounced), queryFn: () => api.directory(debounced), enabled: open });
  const options: Principal[] = [
    ...(props.allowEveryone && t("Everyone").toLowerCase().includes(q.trim().toLowerCase())
      ? [{ principal_type: "everyone" as const, principal_id: 0, name: t("Everyone"), detail: t("All users") }]
      : []),
    ...(results.data ?? []),
  ];

  if (props.value) {
    const Icon = PRINCIPAL_ICON[props.value.principal_type];
    return (
      <div className="flex h-8 min-w-0 flex-1 items-center gap-2 rounded-md border bg-muted/50 px-2 text-sm">
        <Icon className="size-4 shrink-0 text-muted-foreground" />
        <span className="truncate">{props.value.name}</span>
        <button type="button" className="ml-auto text-muted-foreground hover:text-foreground" aria-label={t("Choose again")} onClick={() => props.onChange(null)}>
          <XIcon className="size-3.5" />
        </button>
      </div>
    );
  }
  return (
    <div className="relative min-w-0 flex-1">
      <Input
        value={q}
        onChange={(e) => setQ(e.target.value)}
        onFocus={() => setOpen(true)}
        onBlur={() => setTimeout(() => setOpen(false), 150)}
        placeholder={t("Enter a username or group name")}
        className="h-8 text-sm"
      />
      {open && options.length > 0 && (
        <div className="absolute top-9 right-0 left-0 z-50 max-h-56 overflow-y-auto rounded-md border bg-popover p-1 shadow-md">
          {options.map((o) => {
            const Icon = PRINCIPAL_ICON[o.principal_type];
            return (
              <button
                key={`${o.principal_type}-${o.principal_id}`}
                type="button"
                onMouseDown={(e) => e.preventDefault()}
                onClick={() => {
                  props.onChange(o);
                  setQ("");
                }}
                className="flex w-full items-center gap-2 rounded px-2 py-1.5 text-left text-sm hover:bg-accent"
              >
                <Icon className="size-4 shrink-0 text-muted-foreground" />
                <span className="truncate">{o.name}</span>
                <span className="ml-auto shrink-0 text-xs text-muted-foreground">{o.principal_type === "group" ? `${t("Groups")} · ${tServer(o.detail)}` : roleDetail(o.detail)}</span>
              </button>
            );
          })}
        </div>
      )}
    </div>
  );
}

function GrantRow(props: { g: Grant; editable: boolean; roles: Role[]; onRole?(r: Role): void; onRemove?(): void; removeLabel?: string }) {
  const { g } = props;
  const Icon = PRINCIPAL_ICON[g.principal_type];
  return (
    <div className="flex items-center gap-2.5 py-2">
      <span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-muted">
        <Icon className="size-4 text-muted-foreground" />
      </span>
      <div className="min-w-0 flex-1">
        <div className="truncate text-sm">
          {principalName(g)}
          {g.principal_type === "group" && <span className="ml-1.5 text-xs text-muted-foreground">{t("Groups")}</span>}
        </div>
        <div className="truncate text-xs text-muted-foreground">
          {g.inherited_from ? t("Inherited from “{name}”", { name: g.inherited_from }) : g.granted_by_name ? t("Granted by {name}", { name: g.granted_by_name }) : t("System default")}
          {g.expires_at && ` · ${tc("date", "Expires {date}", { date: formatDate(g.expires_at) })}`}
        </div>
      </div>
      {props.editable && props.onRole ? (
        <NativeSelect size="sm" value={g.role} onChange={(e) => props.onRole!(e.target.value as Role)} aria-label={t("Role")}>
          {props.roles.map((r) => (
            <option key={r} value={r}>
              {ROLE_LABEL[r]}
            </option>
          ))}
        </NativeSelect>
      ) : (
        <span className="text-xs text-muted-foreground">{ROLE_LABEL[g.role]}</span>
      )}
      {props.onRemove && (
        <Button size="icon-sm" variant="ghost" title={props.removeLabel ?? t("Remove")} aria-label={props.removeLabel ?? t("Remove")} onClick={props.onRemove}>
          <XIcon />
        </Button>
      )}
    </div>
  );
}

/** Manage access: space root folder = space members; other folders / files = sharing */
export function AccessDialog({ nodeId, onClose }: { nodeId: string; onClose(): void }) {
  const me = useMe();
  const qc = useQueryClient();
  const q = useQuery({ queryKey: keys.access(nodeId), queryFn: () => api.access(nodeId) });
  const [principal, setPrincipal] = useState<Principal | null>(null);
  const [role, setRole] = useState<Role>("viewer");
  const [days, setDays] = useState(0);

  const refresh = () => {
    void refreshFiles(qc, { access: [nodeId] });
  };

  const add = useMutation({
    mutationFn: (req: { principal_type: PrincipalType; principal_id: number; role: Role; expires_at: number | null }) => api.grant(nodeId, req),
    onSuccess: () => {
      setPrincipal(null);
      refresh();
      toast.success(t("Access updated"));
    },
  });
  const remove = useMutation({
    mutationFn: (id: number) => api.revoke(id),
    onSuccess: () => refresh(),
    onError: (e) => toast.error(e.message),
  });
  const [ask, question] = useConfirm();
  const confirmRemove = async (g: Grant, self: boolean) => {
    const name = info?.is_drive_root ? info.drive.name : (info?.node.name ?? "");
    const ok = await ask(
      self
        ? {
            title: t("Leave “{name}”?", { name }),
            description: t("You'll lose your access to it right away. Only someone who manages it can give it back."),
            confirmText: t("Leave"),
            destructive: true,
          }
        : {
            title: t("Remove access for {name}?", { name: principalName(g) }),
            description: t("They'll lose their access to it right away. You can give it back later."),
            confirmText: t("Remove"),
            destructive: true,
          },
    );
    // Once you have left, there is nothing more here for you to see, nor loaded inside it
    if (ok)
      remove.mutate(g.id, {
        onSuccess: () => {
          if (!self) return;
          void refreshFiles(qc, { left: [nodeId] });
          onClose();
        },
      });
  };

  const info = q.data;
  const personalRoot = info?.drive.kind === "personal" && info.is_drive_root;
  const roles: Role[] = info?.is_drive_root && info.drive.kind === "team" ? ["viewer", "editor", "manager", "owner"] : ["viewer", "editor", "manager"];
  const title = info ? (info.is_drive_root ? t("Members of “{name}”", { name: info.drive.name }) : t("Share “{name}”", { name: info.node.name })) : t("Manage access");

  return (
    <Dialog open onOpenChange={(o) => !o && onClose()}>
      <DialogContent className="sm:max-w-lg">
        {question}
        <DialogHeader>
          <DialogTitle className="truncate pr-8">{title}</DialogTitle>
          <DialogDescription>
            {info?.is_drive_root
              ? t("Members can access all files in this space.")
              : t("People you share with can access this item (for a folder, everything in it). It appears in their Shared with me.")}
          </DialogDescription>
        </DialogHeader>

        {!info ? (
          <Pending
            query={q}
            compact
            loading={
              <div className="flex h-32 items-center justify-center text-muted-foreground">
                <Loader2Icon className="size-5 animate-spin" />
              </div>
            }
          />
        ) : personalRoot ? (
          <p className="rounded-md bg-muted/60 p-3 text-sm text-muted-foreground">{t("A personal space can't be shared as a whole. Right-click a folder in it and choose Share with….")}</p>
        ) : (
          <>
            {info.can_manage && (
              <form
                className="grid gap-2"
                onSubmit={(e) => {
                  e.preventDefault();
                  if (!principal) return;
                  add.mutate({
                    principal_type: principal.principal_type,
                    principal_id: principal.principal_id,
                    role,
                    expires_at: days ? Math.floor(Date.now() / 1000) + days * 86400 : null,
                  });
                }}
              >
                <div className="flex gap-2">
                  <PrincipalPicker value={principal} onChange={setPrincipal} allowEveryone={info.drive.kind !== "personal"} />
                  <NativeSelect size="sm" value={role} onChange={(e) => setRole(e.target.value as Role)} aria-label={t("Role")}>
                    {roles.map((r) => (
                      <option key={r} value={r}>
                        {ROLE_LABEL[r]}
                      </option>
                    ))}
                  </NativeSelect>
                  <NativeSelect size="sm" value={days} onChange={(e) => setDays(Number(e.target.value))} aria-label={tc("short", "Expiration")}>
                    {EXPIRY.map((x) => (
                      <option key={x.days} value={x.days}>
                        {x.label}
                      </option>
                    ))}
                  </NativeSelect>
                  <Button type="submit" size="sm" className="h-8" disabled={!principal || add.isPending}>
                    {add.isPending && <Loader2Icon className="animate-spin" />}
                    {t("Add")}
                  </Button>
                </div>
                <p className="text-xs text-muted-foreground">{t("{role}: {hint}", { role: ROLE_LABEL[role], hint: ROLE_HINT[role] })}</p>
                <ErrorText>{add.error?.message}</ErrorText>
              </form>
            )}

            <div className="max-h-[50vh] overflow-y-auto">
              <div className="divide-y">
                {info.direct.map((g) => {
                  const self = g.principal_type === "user" && g.principal_id === me.id;
                  const canLeave = self && g.role !== "owner" && !info.is_drive_root;
                  return (
                    <GrantRow
                      key={g.id}
                      g={g}
                      roles={roles}
                      editable={info.can_manage}
                      onRole={(r) => add.mutate({ principal_type: g.principal_type, principal_id: g.principal_id, role: r, expires_at: g.expires_at })}
                      onRemove={info.can_manage || canLeave ? () => confirmRemove(g, self) : undefined}
                      removeLabel={canLeave && !info.can_manage ? t("Leave") : t("Remove")}
                    />
                  );
                })}
                {info.direct.length === 0 && info.inherited.length === 0 && <p className="py-4 text-center text-sm text-muted-foreground">{t("Not shared with anyone yet")}</p>}
              </div>
              {info.inherited.length > 0 && (
                <>
                  <div className="mt-3 mb-1 text-xs font-medium text-muted-foreground">{t("Inherited (managed in a parent folder or the space)")}</div>
                  <div className={cn("divide-y opacity-80")}>
                    {info.inherited.map((g) => (
                      <GrantRow key={`i${g.id}`} g={g} roles={roles} editable={false} />
                    ))}
                  </div>
                </>
              )}
            </div>
            {!info.can_manage && (
              <p className="text-xs text-muted-foreground">
                {atLeast(info.my_role, "manager") && !me.can_share
                  ? t("Your account isn't allowed to share, so you can't change who has access. Ask an administrator.")
                  : t("Your role is “{role}”. Only managers can change access.", { role: info.my_role ? ROLE_LABEL[info.my_role] : "—" })}
              </p>
            )}
          </>
        )}
      </DialogContent>
    </Dialog>
  );
}
